# Generated by Django 3.2.7 on 2024-08-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/tools/'),
        ),
    ]
